package main

import (
	"fmt"
)

func main() {
	str := "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODI4NzQzNDksImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTU4Mjg3MDc0OSwidWlkIjoxLCJ1bmFtZSI6ImFkbWluIn0.PXlgEEjCNNB4DNy1h6j58HvXpWdKSMvGzwpjGcKqp9VMOCRcMetS4V4NInxvjEn7nm-qjWSAZud_f28BgLojitbFJIzC_N5aUCNgrEqxBnAsbsdpCjY6HXuXwWe5cf0sTbldR1riv1Rzurq-5FKRdqBGseW_Y9QCIRPO76UPnBY"
	fmt.Println(len(str))
}
